// Mock data for BookMyVenue Admin Dashboard

export const mockAdminUser = {
  id: 1,
  name: 'Admin User',
  email: 'admin@bookmymandap.com',
  phone: '+91-9876543210',
  address: '123 Admin Street, City, State 123456',
  role: 'Admin',
  joinDate: '2025-01-15',
};

export const mockKPIs = {
  totalUsers: 1284,
  totalVenues: 342,
  totalBookings: 2891,
  revenue: 184000, 
};

export const mockUserBreakdown = [
  { type: 'Customers', count: 1000 },
  { type: 'Venue Owners', count: 284 },
];

export const mockVenueStatus = [
  { status: 'Approved', count: 300 },
  { status: 'Pending', count: 32 },
  { status: 'Rejected', count: 10 },
];

export const mockRecentBookings = [
  {
    id: 'BK001',
    customer: 'Rushikesh Dudhal',
    mobile: '9876543210',
    venue: 'Mezza nine',
    owner: 'Ritesh',
    startDate: '2026-06-15',
    endDate: '2026-06-16',
    guests: 150,
    cost: 50000,
    status: 'Confirmed',
  },
  {
    id: 'BK002',
    customer: 'Nikita Palde',
    mobile: '8765432109',
    venue: 'Riverside Resort',
    owner: 'Kunal Sharma',
    startDate: '2026-06-20',
    endDate: '2026-06-21',
    guests: 200,
    cost: 75000,
    status: 'Pending',
  },
  {
    id: 'BK003',
    customer: 'Sushant Waghmare',
    mobile: '7654321098',
    venue: 'Sunbeam',
    owner: 'Neha Datir',
    startDate: '2026-06-10',
    endDate: '2026-06-11',
    guests: 300,
    cost: 100000,
    status: 'Completed',
  },
  {
    id: 'BK004',
    customer: 'Vedant Desai',
    mobile: '6543210987',
    venue: 'Sunset Gardens',
    owner: 'Neeti',
    startDate: '2026-06-25',
    endDate: '2026-06-26',
    guests: 120,
    cost: 45000,
    status: 'Confirmed',
  },
  {
    id: 'BK005',
    customer: 'Pooja Jaiswal',
    mobile: '5432109876',
    venue: 'Crystal Hall',
    owner: 'Divya Deshmukh',
    startDate: '2026-07-01',
    endDate: '2026-07-02',
    guests: 250,
    cost: 80000,
    status: 'Cancelled',
  },
];

export const mockAllBookings = [
  ...mockRecentBookings,
  {
    id: 'BK006',
    customer: 'Vishal Borle',
    mobile: '4321098765',
    venue: 'Sunbeam Hinjewadi',
    owner: 'Virendra',
    startDate: '2026-07-05',
    endDate: '2026-07-06',
    guests: 180,
    cost: 60000,
    status: 'Confirmed',
  },
  {
    id: 'BK007',
    customer: 'Ashish Shinde',
    mobile: '3210987654',
    venue: 'Sunbeam Karad',
    owner: 'Sneha Bhat',
    startDate: '2026-07-10',
    endDate: '2026-07-11',
    guests: 220,
    cost: 70000,
    status: 'Pending',
  },
];

export const mockPendingVenues = [
  {
    id: 'V001',
    name: 'Dream Palace',
    owner: 'Sandesh ',
    city: 'Mumbai',
    capacity: 500,
    pricePerDay: 50000,
    amenities: ['AC', 'Parking', 'Catering', 'WiFi'],
    description: 'Beautiful palace with modern amenities',
    images: ['palace1.jpg', 'palace2.jpg'],
    submittedDate: '2026-06-01',
  },
  {
    id: 'V002',
    name: 'Lakeside Resort',
    owner: 'Aditya Sable',
    city: 'Pune',
    capacity: 300,
    pricePerDay: 35000,
    amenities: ['AC', 'Pool', 'Catering', 'Decoration'],
    description: 'Scenic lakeside venue perfect for weddings',
    images: ['lake1.jpg', 'lake2.jpg'],
    submittedDate: '2026-06-02',
  },
  {
    id: 'V003',
    name: 'Urban Lofts',
    owner: 'Shubham ',
    city: 'Bangalore',
    capacity: 150,
    pricePerDay: 25000,
    amenities: ['Modern', 'WiFi', 'Parking', 'Catering'],
    description: 'Contemporary urban venue for corporate events',
    images: ['loft1.jpg', 'loft2.jpg'],
    submittedDate: '2026-06-03',
  },
];

export const mockApprovedVenues = [
  {
    id: 'V101',
    name: 'Grand Ballroom',
    owner: 'Vaibhav',
    city: 'Delhi',
    capacity: 800,
    pricePerDay: 100000,
    amenities: ['AC', 'Parking', 'Catering', 'WiFi', 'Decoration'],
    status: 'Approved',
    bookings: 45,
    rating: 4.8,
  },
  {
    id: 'V102',
    name: 'Riverside Resort',
    owner: 'Vrushabh',
    city: 'Goa',
    capacity: 600,
    pricePerDay: 75000,
    amenities: ['Beach', 'Pool', 'Catering', 'WiFi'],
    status: 'Approved',
    bookings: 38,
    rating: 4.6,
  },
  {
    id: 'V103',
    name: 'Heritage Palace',
    owner: 'Nikita',
    city: 'Jaipur',
    capacity: 1000,
    pricePerDay: 120000,
    amenities: ['Heritage', 'Parking', 'Catering', 'WiFi', 'Decoration'],
    status: 'Approved',
    bookings: 52,
    rating: 4.9,
  },
];

export const mockReviews = [
  {
    id: 'R001',
    venue: 'Grand Ballroom',
    customer: 'Sushant',
    rating: 5,
    text: 'Excellent venue! Perfect for our wedding. Staff was very helpful.',
    date: '2026-05-20',
    isSpam: false,
  },
  {
    id: 'R002',
    venue: 'Riverside Resort',
    customer: 'Nikita',
    rating: 4,
    text: 'Great location and beautiful setup. Highly recommended!',
    date: '2026-05-18',
    isSpam: false,
  },
  {
    id: 'R003',
    venue: 'Heritage Palace',
    customer: 'Vedant ',
    rating: 3,
    text: 'Good venue but could improve on catering quality.',
    date: '2026-05-15',
    isSpam: false,
  },
  {
    id: 'R004',
    venue: 'Pearl Banquet',
    customer: 'Unknown User',
    rating: 1,
    text: 'BUY CHEAP DECORATIONS HERE!!! CLICK LINK!!!',
    date: '2026-05-10',
    isSpam: true,
  },
  {
    id: 'R005',
    venue: 'Crystal Hall',
    customer: 'Deven Deshmukh',
    rating: 5,
    text: 'Outstanding service and beautiful ambiance. Will definitely book again!',
    date: '2026-05-08',
    isSpam: false,
  },
  {
    id: 'R006',
    venue: 'Sunset Gardens',
    customer: 'Aditi',
    rating: 2,
    text: 'Disappointed with the cleanliness and maintenance.',
    date: '2026-05-05',
    isSpam: false,
  },
];

export const mockPaymentTransactions = [
  {
    id: 'PT001',
    bookingId: 'BK001',
    customer: 'Nikita ',
    amount: 50000,
    method: 'Credit Card',
    status: 'Success',
    date: '2026-06-14',
  },
  {
    id: 'PT002',
    bookingId: 'BK002',
    customer: 'Vedant',
    amount: 75000,
    method: 'Debit Card',
    status: 'Success',
    date: '2026-06-19',
  },
  {
    id: 'PT003',
    bookingId: 'BK003',
    customer: 'Sushant',
    amount: 100000,
    method: 'Net Banking',
    status: 'Success',
    date: '2026-06-09',
  },
  {
    id: 'PT004',
    bookingId: 'BK004',
    customer: 'Desai',
    amount: 45000,
    method: 'Wallet',
    status: 'Failed',
    date: '2026-06-24',
  },
  {
    id: 'PT005',
    bookingId: 'BK005',
    customer: 'Rushi Dudhal',
    amount: 80000,
    method: 'Credit Card',
    status: 'Pending',
    date: '2026-06-30',
  },
];

export const mockCommissionData = {
  totalCommission: 45600,
  monthlyCommission: 12000,
  pendingCommission: 5000,
  transactions: [
    {
      id: 'C001',
      bookingId: 'BK001',
      venue: 'Miramar Goa',
      bookingAmount: 50000,
      commissionRate: 3,
      commissionAmount: 1500,
      date: '2026-06-15',
      status: 'Paid',
    },
    {
      id: 'C002',
      bookingId: 'BK002',
      venue: 'Panaji Casino  ',
      bookingAmount: 75000,
      commissionRate: 3,
      commissionAmount: 2250,
      date: '2026-06-20',
      status: 'Paid',
    },
    {
      id: 'C003',
      bookingId: 'BK003',
      venue: 'Heritage Palace',
      bookingAmount: 100000,
      commissionRate: 3,
      commissionAmount: 3000,
      date: '2026-06-10',
      status: 'Paid',
    },
    {
      id: 'C004',
      bookingId: 'BK004',
      venue: 'Sunset Gardens',
      bookingAmount: 45000,
      commissionRate: 3,
      commissionAmount: 1350,
      date: '2026-06-25',
      status: 'Pending',
    },
  ],
};
